### PR TITLE
Add line of best fit, update chart.js, fix issues

### LINKED ISSUE #54: [Bug]: Incorrect Y value of bar chart after exporting to PDF
### Describe the bug

A simple bar chart that works fine in the preview window, but the Y value is not correct after exporting the PDF.

**Y is 7**

```chart
type: bar
labels: [TESTA]
series:
  - title: AAA
    data: [7]
tension: 0.2
width: 80%
labelColors: false
fill: false
beginAtZero: false
```
preview window:
image

PDF: **Y is 6.6**
image

### Relevant errors (if available)

_No response_

### Steps to reproduce

1. Create a bar chart with a Y value of 7
2. Renders without problems in preview mode
3. Exported to PDF, the Y value became 6.6

### Expected Behavior

Also has the correct Y value when exporting to PDF

### Additional context

Obsidian：v0.14.2
Obsidian Charts: v3.5.1

### Code

_No response_

### Operating system

Windows

### PR DESCRIPTION
**Pull request by Wemmy0**
Fixes #54 
Adds enhancement #65 

USAGE:
1. Add bestFit: true (optional) to the chart code
2. Add bestFitTitle: "Your Title" (Optional) to the chart code to change the generated line title
3. Add bestFitNumber: <ID of line> (Optional) to the chart code to specify which line should be used to create the line of best fit

Other changes:
- Updates chart.js for much better performance and hybrid charts (not implemented yet)

How it works:
- Uses the linear regression method to create the equation of the line
- Then using the Y values and the equation of the line, to form points for the line of best fit
- Then append a new line to the chart data which is passed on to the normal chart renderer

Example:
```chart
type: line
labels: [0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
series:
  - title: 
    data: [0.0137, 0.0189, 0.0217, 0.0239, 0.03, 0.033, 0.0371, 0.0446]
  - title: 
    data: [0, 0.001, 0.002]
width: 100%
beginAtZero: false
xTitle: "Length /cm"
yTitle: "1/f"
bestFit: true
bestFitTitle: "LOBF"
bestFitNumber: 1
```
Forms:
image

If bestFitTitle or bestFitNumber aren't defined, they default to the values `Line of Best Fit` and `0` respectively
With default values:
image

The PDF exporting issue was fixed by passing through the setting animation duration 0 to chart.js to disable the animation.

### CODE REVIEW

**Comment by Wemmy0** [comment]
[obsidian-charts.zip](https://github.com/phibr0/obsidian-charts/files/9994986/obsidian-charts.zip)
Try it with this compiled version.
Tested on iOS and arch linux without any issues.

**Comment by phibr0** [comment]
Looks good, but it seems like you changed the codeblock type for the advanced-chart. This will break exisiting codeblocks by other users. can you change it back?

**Comment by Wemmy0** [comment]
Yep sorry changing it back now

**Comment by Wemmy0** [comment]
[obsidian-charts.zip](https://github.com/phibr0/obsidian-charts/files/9995000/obsidian-charts.zip)
That's the one with the correct manifest.json file

**Comment by phibr0** [comment]
Thanks a lot for your improvements!

**Pull request merged**
